# Generated by Django 5.1.1 on 2024-09-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='store',
            new_name='Product',
        ),
    ]
