# Generated by Django 5.1.1 on 2024-10-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_rename_store_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
