# Generated by Django 5.1.1 on 2024-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_delete_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=0, height_field=100, upload_to='imagess', width_field=100),
        ),
    ]
