# Generated by Django 5.1.1 on 2024-10-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
